version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry-app
    volumes:
      - ./command:/app/command
      - ./telemetry:/app/telemetry
